---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-deployment
  namespace: dice-app
  labels:
    app: dice
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'

    profiles.grafana.com/cpu.scrape: 'true'
    profiles.grafana.com/cpu.port: '8080'
    profiles.grafana.com/memory.scrape: 'true'
    profiles.grafana.com/memory.port: '8080'
    profiles.grafana.com/goroutine.scrape: 'true'
    profiles.grafana.com/goroutine.port: '8080'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice
  template:
    metadata:
      namespace: dice-app
      labels:
        app: dice
    spec:
      containers:
        - name: dice
          image: 'fagdtw/dice-app'
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: dice-app/dice
            - name: PYROSCOPE_HOST
              value: http://grafana-alloy.monitoring.svc.cluster.local:4040
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://grafana-alloy.monitoring.svc.cluster.local:4318
            # - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
            #   # value: http://tempo.monitoring:4318
            #   # value: http://tempo.monitoring.svc.cluster.local:4318/v1/traces
            #   value: http://grafana-alloy.monitoring:12345/v1/traces
            # - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
            #   value: http://grafana-alloy.monitoring:12345/v1/metrics
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.name=dice,service.version=0.1.0
          resources:
            limits:
              memory: "75Mi"
              cpu: "500m"
