---
opentelemetry-collector:
  config:
    exporters:
      otlphttp/example:
        endpoint: http://grafana-alloy:4318

    service:
      pipelines:
        traces:
          exporters: [otlphttp/example]
        logs:
          exporters: [otlphttp/example]
        metrics:
          exporters: [otlphttp/example]
jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

opensearch:
  enabled: false
