---
opentelemetry-collector:
  config:
    exporters:
      otlphttp/alloy:
        endpoint: http://grafana-alloy.monitoring:4318

      otlphttp/tempo:
        endpoint: http://tempo.monitoring:4318

    service:
      pipelines:
        traces:
          exporters: [spanmetrics, otlphttp/tempo]
        logs:
          exporters: [otlphttp/alloy]
        metrics:
          exporters: [otlphttp/alloy]
jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

opensearch:
  enabled: false
