---
opentelemetry-collector:
  config:
    exporters:
      otlphttp/example:
        endpoint: http://grafana-alloy:4318

      otlp/tempo:
        endpoint: tempo:4317

    service:
      pipelines:
        traces:
          exporters: [spanmetrics, otlphttp/example, otlp/tempo]
        logs:
          exporters: [otlphttp/example, otlp/tempo]
        metrics:
          exporters: [otlphttp/example, otlp/tempo]
jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false

opensearch:
  enabled: false
