{
 "title": "User Diagnostics Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "username", "label": "Username", "query": "Flavio" }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Dice Rolls",
   "type": "timeseries",
   "description": "A sample from the rolls the user got!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "dice_rolls_byUser{user_name=\"$username\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "filters": [
      {
       "id": "d09c86fb",
       "isCustomValue": false,
       "operator": "=",
       "scope": "span",
       "tag": "user.name",
       "value": [ "$username" ],
       "valueType": "string"
      }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{span.user.name=\"$username\"}",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "Logs related to the specified user",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{namespace=\"dice-app\"} |= \"$username\""
    }
   ]
  }
 ]
}