---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-sources-conf
  labels:
    name: grafana-sources-conf
  namespace: test

data:
  datasources.yaml: |-
    datasources:
      - name: Prometheus
        type: prometheus
        url: "http://prometheus.test:8080"
      - name: Loki
        type: loki
        url: "http://loki-gateway.loki:80"
      - name: Jaeger
        type: jaeger
        url: "http://jaeger-inmemory-instance-collector.test:16686"
