---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-sources-conf
  labels:
    name: grafana-sources-conf
  namespace: monitoring

data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.monitoring:8080
      - name: Loki
        type: loki
        url: http://loki-gateway.monitoring:80
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: Tribal
      - name: Tempo
        type: tempo
        url: http://tempo-simplest-query-frontend.monitoring:16687
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: Tribal
