---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-sources-conf
  labels:
    name: grafana-sources-conf
  namespace: monitoring

data:
  datasources.yaml: |-
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus.monitoring:8080
      - name: Loki
        type: loki
        uid: Loki
        url: http://loki-gateway.monitoring:80
        jsonData:
          httpHeaderName1: X-Scope-OrgID
        secureJsonData:
          httpHeaderValue1: Tribal
      - name: Tempo
        type: tempo
        url: http://tempo-gateway.monitoring:80
        jsonData:
          httpHeaderName1: X-Scope-OrgID
          tracesToLogsV2:
            datasourceUid: Loki
            # tags: [{key: 'job'}, {key: 'instance'}, {key: 'pod'}, {key: 'namespace'}, { key: 'service.name', value: 'service_name' }]
            tags:
              - key: service.name
                value: service_name
              - key: namespace
              - key: trace_id
                value: TraceID
            spanStartTimeShift: '-1h'
            spanEndTimeShift: '1h'
            filterByTraceID: true
            filterBySpanID: false
            # customQuery: true
            # query: '{service_name="$${__tags.app}"} |= "$${__trace.traceId}"'
            # query: '{service_name="$${__tags.service_name}"} | json | logfmt | drop __error__, __error_details__ | TraceID="__trace.traceId"'
            # query: '{service_name="$${__tags.service_name}"} | label_format log_line_contains_trace_id=`{{ contains "$${__trace.traceId}" __line__  }}` | log_line_contains_trace_id="true" or TraceID="$${__trace.traceId}"'
          lokiSearch:
            datasourceUid: 'Loki'
          serviceMap:
            datasourceUid: 'Prometheus'
          nodeGraph:
            enabled: true

        secureJsonData:
          httpHeaderValue1: Tribal
