---
multitenancyEnabled: false
streamOverHTTPEnabled: true

traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo-traces
      endpoint: minio.monitoring.svc.cluster.local:9000
      access_key: admin
      secret_key: password123
      insecure: true

ingester:
  replicas: 2  # 2 is the minimum! It doesn't work with 1
  zoneAwareReplication:
    enabled: false

metricsGenerator:
  enabled: true
  replicas: 1
  config:
    registry:
      collection_interval: 15s
    # processor:
    #   span_metrics:
    #     dimensions:
    #       - span-metrics-latency
    #       - span-metrics-count
    #       - span-metrics-size
    #   service_graphs:
    #     dimensions:
    #       - traces_service_graph_request_total
    #       - traces_service_graph_request_failed_total
    #       - traces_service_graph_request_server_seconds
    #       - traces_service_graph_request_client_seconds
    #       - traces_service_graph_request_messaging_system_seconds
  storage:
    remote_write_add_org_id_header: false
    remote_write:
      - url: http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write
        send_exemplars: true

# Actually generate metrics!
overrides:
  defaults:
    metrics_generator:
      processors:
        - local-blocks
        - service-graphs
        - span-metrics

distributor:
  replicas: 1
  config:
    log_received_spans:
      enabled: true
    log_discarded_spans:
      enabled: true

compactor:
  replicas: 1

querier:
  replicas: 1

query-frontend:
  replicas: 1

tempoQuery:
  enabled: true

minio:
  enabled: false

gateway:
  enabled: true
  service:
    type: ClusterIP
