---
apiVersion: v1
kind: Service
metadata:
  name: dice-service
  namespace: ebpf-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9100'
spec:
  type: LoadBalancer
  selector:
    app: ebpf-dice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
